### ISSUE TITLE
graphic visualization problem in Zenfone 5 Android 4.4.2 KitKat

### ISSUE THREAD

**Issue by chigi** [dspachos/whaam-mobileapp#12]
I want to report the following issue:
A strange visualization effect (a black line) appears when I access in the observation panel.
I tried with other devices and the bug is no happened.
have you any idea?
![screenshot_2015-03-10-11-38-27](https://cloud.githubusercontent.com/assets/7777717/6635970/bdf2bc7c-c96b-11e4-97e5-f074f1790789.jpg)

**Comment by dspachos** [comment]
@chigi  
- Did the other devices run Android 4.4.2?
- Can you plz try on another device with the same OS?

**Comment by chigi** [comment]
- Did the other devices run Android 4.4.2?
- Can you plz try on another device with the same OS?

I tried the app in the Samsung S4 with Android 4.4.2 and the problem did
not happen

2015-03-17 9:27 GMT+01:00 Dimitris Spachos notifications@github.com:

**Comment by dspachos** [comment]
Ok, I'll close the issue until we have something new to reproduce the bug.
