### ISSUE TITLE
Turn-off capitalization on the login username field

### ISSUE THREAD

**Issue by gianluca78** [dspachos/whaam-mobileapp#16]
Hi @dspachos,
in the login screen, the username field has activated an automated capitalization. This is very annoying for me. I think you could disable it using the autocorrect and autocapitalize properties (at least on iOS):

`<input type="text" autocorrect="off" autocapitalize="off">`

**Comment by dspachos** [comment]
Not in my iPhone. What iOS version do you have?

**Comment by gianluca78** [comment]
I have an iPhone 5S with iOS 8.2
