### ISSUE TITLE
The timer doesn't work as a background process

### ISSUE THREAD

**Issue by gianluca78** [dspachos/whaam-mobileapp#18]
Hi @dspachos,
some parents discovered that when the mobile phone goes to stand by or they receive a call or a message the timer of the observation stop to count the time. As a consequence, the period of observation is compromised because a session could last forever if the app is not active and users could take wrong timestamps.

This is particularly problematic when user plans to observe for a long period (i. e. 40 minutes).

I think this is the most urgent fix to do in the mobile now. The process should run also in background... Is it possible?

Thank you.

**Comment by dspachos** [comment]
When an application goes to the background, the OS saves the current state of the app and when the app is resumed, it's reloading the latest saved state. So, it's no possible for the timer to run on the background. 
What I can try is to try to determinate the two events (minimise and resume) and save the clock time (in some way) and try to adjust the timer. I think it's possible (although it may need to completely rewrite the function).

**Comment by gianluca78** [comment]
Antonella decided to leave things as they are. We can discuss about this for a future release...
