### ISSUE TITLE
iOS 9.0.2 compatibility

### ISSUE THREAD

**Issue by gianluca78** [dspachos/whaam-mobileapp#20]
The app has a strange behaviour with iOS 9.0.2. The screens are often overlapped and the observation doesn't work anymore. 

![img_2719](https://cloud.githubusercontent.com/assets/1150210/10507717/c7de6e1e-7322-11e5-9124-6e578391a9dd.PNG)

**Comment by dspachos** [comment]
Thanks for mentioning Gianluca!
The bug is already fixed (patch from https://gist.github.com/IgorMinar/863acd413e3925bf282c)
and will be updated during next days.
