### ISSUE TITLE
Child Overview

### ISSUE THREAD

**Issue by chigi** [dspachos/whaam-mobileapp#3]
I have created a new user and I have Insert a new child.
When I access with the mobile application using the new credential of the new user, the Child Overview in the summary panel, shows a little wrong in the visualization of the age. The panel shows the following data:  “2015. Years old”. 
Here below the screenshot of the bug.

![error](https://cloud.githubusercontent.com/assets/7777717/5904382/3b16cca0-a588-11e4-9821-2c4b9d70934c.png)

**Comment by dspachos** [comment]
Currently the bug is caused because the parameter 'name' for the user testp/testp is missing.
Could you please add  
"surname": "",
"name": "",
for the user testp/testp and try again?
The same goes for the child network (name and surname are missing). Could you please fix them too?

Additionally, can you please inform me about what fields are mandatory on the web app? (in order to avoid such bugs in the future).

**Comment by gianluca78** [comment]
Ok, I will provide you with a list of mandatory/not mandatory parameters as soon as possible.

**Comment by gianluca78** [comment]
Sent!

**Comment by dspachos** [comment]
"userIsObserver": true,
"userIsAllowedToTakeABCs": true,

If this information is missing, what should be the default action? Allow the user to observer or no?

**Comment by gianluca78** [comment]
These information should be always displayed with boolean values. The only variables that can be missing are:
- plannedNumberOfObservations
- gatheredNumberOfObservations

when **userIsObserver** is false and
- gatheredNumberOfABCs

when **userIsAllowedToTakeABCs** is false

I'm realizing that maybe it's better to display always the complete set of variables. Removing fields is only a bit confusing. What do you think?

**Comment by dspachos** [comment]
Agree. Display complete set of variables, otherwise is a bit confusing. So, if I understand well, these variables will always have some value (otherwise I have to check first for existence!)

**Comment by gianluca78** [comment]
Ok, changed. These variable have now always some value.
