### ISSUE TITLE
Observation button

### ISSUE THREAD

**Issue by gianluca78** [dspachos/whaam-mobileapp#6]
The button to count (or start-stop the timer in the duration format) behavior occurrences in the observation feature is too small. I think it could be more usable if it could be a lot bigger so as the user has not to watch the screen during the observation process because the button is... properly under his thumb.

**Comment by dspachos** [comment]
@gianluca78 : the button is full width (of the current screen size). Of course I can make it bigger, but I was planning to use the bottom half of the screen for the list items. Moreover, I plan to add a swipe to delete button for accidentally observed behaviours.

**Comment by gianluca78** [comment]
Full width? I have seen it super tiny! I will verify tomorrow and I will let you know (I have not an Android mobile phone at home!). ;-)

**Comment by dspachos** [comment]
Yes, can you send a screenshot plz? Take a look how it suppose to be:
![img_1676](https://cloud.githubusercontent.com/assets/6309422/6036318/1784d26c-ac4c-11e4-9d8f-931fc47ec887.PNG)

**Comment by gianluca78** [comment]
I think I made a mistake. Everything seems to be ok. Nevermind!
