### ISSUE TITLE
Redirect after frequency observation

### ISSUE THREAD

**Issue by gianluca78** [dspachos/whaam-mobileapp#9]
I have a problem with the frequency (I have still not tried the duration) observation on my iPhone 5S with iOS 8.1.3 and the Ionic View 1.0.5.

When I complete the observation, the data is correctly saved but the user is not redirected to the assessment screen. 

I tried the same feature on an Android device but the bug is not present there. I tried on the Antonella's iPhone (same model) and everything is fine. How can I help you to debug?

PS.
In the first release the redirect worked perfectly.

**Comment by dspachos** [comment]
@gianluca78 
You  have to send me your username/password, the child nickname and the exactly behavior assessment.I'll try to re-produce the problem.

**Comment by gianluca78** [comment]
Ok. 

Username: gianlucamerlo
Pwd: testtest

There is only one child and one assessment. 

Thanks!

**Comment by gianluca78** [comment]
@dspachos I discovered that this error has been caused by me while I forced in the backend the assessment dates. We can close the issue for this moment.

**Comment by dspachos** [comment]
@gianluca78 Can you please give me more details on this? I didn't understand what you did..

**Comment by gianluca78** [comment]
I made a mistake forcing the baseline and intervetion dates from the backend. As a consequence, when I saved the observation data, the server returned a 500 error and the redirect were not performed.
